# HTTP Server
server:
  port: 8888

spring:
  application:
    name: discovery-service
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JGasconRueda/SpringCloudConfig-GitRepository
          clone-on-start: true